### ISSUE TITLE
Seeing Error : Cannot set property 'flags' of undefined

### ISSUE THREAD

**Issue by robpolak** [node-cache/node-cache#127]
This error has cropped up recently, I have not modified this code in some time.  Looks related to some internal package :  URL.onParseComplete (internal/url.js:226:13) .. no clue what is going on.  If I stringify my object it seems to work no problem 

working code:

`
this.tokenCache.set(token, json.stringify(object), ttl);
`

non-working code:

`
this.tokenCache.set(token, object, ttl);
`

package.json :

> "node-cache": "^4.2.0",

Stack Trace : 
> Cannot set property 'flags' of undefined .. TypeError: Cannot set property 'flags' of undefined
>     at URL.onParseComplete (internal/url.js:226:13)
>     at URL.set [as href] (internal/url.js:444:7)
>     at _clone (../node_modules/clone/clone.js:162:16)
>     at _clone (../node_modules/clone/clone.js:162:18)
>     at clone (../node_modules/clone/clone.js:202:10)
>     at NodeCache.module.exports.NodeCache._wrap (../node_modules/node-cache/lib/node_cache.js:406:22)

**Comment by erdii** [comment]
Maybe you need to disable clone mode, because your token objects aren't POJO (plain old js objects), but they are more complex, like having circular refs, functions etc...

```js
const myCache = new NodeCache({
  useClones: false,
});
```

**Comment by robpolak** [comment]
This did seem to fix my issue, however, it was an array where 

```
[
{pojo object},
true
]
```
I am thinking that was the issue.

**Comment by iambalaam** [comment]
I've just come accross this issue.  It looks like the change is due to URL being added to the global scope in node10.

This will throw in node10 and node12, but is fine in node8
```
> const NodeCache = require('node-cache');
> const n = new NodeCache();
> n.set('url', new URL('https://example.com'))

Thrown:
TypeError: Cannot set property 'flags' of undefined
    at URL.onParseComplete (internal/url.js:224:13)
    at URL.set [as href] (internal/url.js:443:7)
    at _clone (/Users/guybal/ws/DVWebNode/src/DVWebNode/node_modules/clone/clone.js:162:16)
    at clone (/Users/guybal/ws/DVWebNode/src/DVWebNode/node_modules/clone/clone.js:202:10)
    at NodeCache._wrap (/Users/guybal/ws/DVWebNode/src/DVWebNode/node_modules/node-cache/lib/node_cache.js:700:24)
    at NodeCache.set (/Users/guybal/ws/DVWebNode/src/DVWebNode/node_modules/node-cache/lib/node_cache.js:435:31)
```

**Comment by erdii** [comment]
will investigate! thank you for reporting and welcome here!

notes to myself:
* build bug test first
* check for updates in our upstream dependency "clone"
* check for workarounds and their performance penalties

**Comment by iambalaam** [comment]
Hi @erdii thanks for the quick reply, but I did a little digging and not a bug in `node-cache` at all.  It's broken in `clone@2.x` which is the most up to date, and the version you're using.

I'll close this, as I have opened https://github.com/pvorb/clone/issues/109
And if I remember I'll comment back here when it's done so people can bump versions

**Comment by erdii** [comment]
Thank you @iambalaam! I'll close this issue when the upstream issue is resolved
